src/Entity/Alumnos.php
<?php

namespace App\Entity;

use App\Repository\AlumnosRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AlumnosRepository::class)]
class Alumnos
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\Column(length: 255)]
    private ?string $primer_apellido = null;

    #[ORM\Column(length: 255)]
    private ?string $segundo_apellido = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fecha_nacimiento = null;

    #[ORM\Column(length: 255)]
    private ?string $domicilio = null;

    #[ORM\Column(length: 255)]
    private ?string $poblacion = null;

    #[ORM\Column]
    private ?int $codigo_postal = null;

    #[ORM\Column(length: 255)]
    private ?string $telefono = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\OneToMany(mappedBy: 'fk_alumno', targetEntity: Alumnoscursos::class)]
    private Collection $alumnoscursos;
    
    public function __toString()
    {
        return $this->nombre;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getPrimerApellido(): ?string
    {
        return $this->primer_apellido;
    }

    public function setPrimerApellido(string $primer_apellido): static
    {
        $this->primer_apellido = $primer_apellido;

        return $this;
    }

    public function getSegundoApellido(): ?string
    {
        return $this->segundo_apellido;
    }

    public function setSegundoApellido(string $segundo_apellido): static
    {
        $this->segundo_apellido = $segundo_apellido;

        return $this;
    }

    public function getFechaNacimiento(): ?\DateTimeInterface
    {
        return $this->fecha_nacimiento;
    }

    public function setFechaNacimiento(\DateTimeInterface $fecha_nacimiento): static
    {
        $this->fecha_nacimiento = $fecha_nacimiento;

        return $this;
    }

    public function getDomicilio(): ?string
    {
        return $this->domicilio;
    }

    public function setDomicilio(string $domicilio): static
    {
        $this->domicilio = $domicilio;

        return $this;
    }

    public function getPoblacion(): ?string
    {
        return $this->poblacion;
    }

    public function setPoblacion(string $poblacion): static
    {
        $this->poblacion = $poblacion;

        return $this;
    }

    public function getCodigoPostal(): ?int
    {
        return $this->codigo_postal;
    }

    public function setCodigoPostal(int $codigo_postal): static
    {
        $this->codigo_postal = $codigo_postal;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(string $telefono): static
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }
    /**
     * @return Collection<int, Alumnoscursos>
     */
    public function getAlumnoscursos(): Collection
    {
        return $this->alumnoscursos;
    }

    public function addAlumnoscurso(Alumnoscursos $alumnoscurso): static
    {
        if (!$this->alumnoscursos->contains($alumnoscurso)) {
            $this->alumnoscursos->add($alumnoscurso);
            $alumnoscurso->setFkAlumno($this);
        }

        return $this;
    }

    public function removeAlumnoscurso(Alumnoscursos $alumnoscurso): static
    {
        if ($this->alumnoscursos->removeElement($alumnoscurso)) {
            // set the owning side to null (unless already changed)
            if ($alumnoscurso->getFkAlumno() === $this) {
                $alumnoscurso->setFkAlumno(null);
            }
        }

        return $this;
    }
}

src/Form/AlumnosType.php
<?php

namespace App\Form;

use App\Entity\Alumnos;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AlumnosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre')
            ->add('primer_apellido')
            ->add('segundo_apellido')
            ->add('fecha_nacimiento')
            ->add('domicilio')
            ->add('poblacion')
            ->add('codigo_postal')
            ->add('telefono')
            ->add('email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Alumnos::class,
        ]);
    }
}

src/Controller/AlumnosController.php
<?php

namespace App\Controller;

use App\Entity\Alumnos;
use App\Form\AlumnosType;
use App\Repository\AlumnosRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/alumnos')]
class AlumnosController extends AbstractController
{
    #[Route('/', name: 'app_alumnos_index', methods: ['GET'])]
    public function index(AlumnosRepository $alumnosRepository): Response
    {
        return $this->render('alumnos/index.html.twig', [
            'alumnos' => $alumnosRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_alumnos_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AlumnosRepository $alumnosRepository): Response
    {
        $alumno = new Alumnos();
        $form = $this->createForm(AlumnosType::class, $alumno);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $alumnosRepository->save($alumno, true);

            return $this->redirectToRoute('app_alumnos_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('alumnos/new.html.twig', [
            'alumno' => $alumno,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_alumnos_show', methods: ['GET'])]
    public function show(Alumnos $alumno): Response
    {
        return $this->render('alumnos/show.html.twig', [
            'alumno' => $alumno,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_alumnos_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Alumnos $alumno, AlumnosRepository $alumnosRepository): Response
    {
        $form = $this->createForm(AlumnosType::class, $alumno);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $alumnosRepository->save($alumno, true);

            return $this->redirectToRoute('app_alumnos_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('alumnos/edit.html.twig', [
            'alumno' => $alumno,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_alumnos_delete', methods: ['POST'])]
    public function delete(Request $request, Alumnos $alumno, AlumnosRepository $alumnosRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$alumno->getId(), $request->request->get('_token'))) {
            $alumnosRepository->remove($alumno, true);
        }

        return $this->redirectToRoute('app_alumnos_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/alumnos/_delete_form.html.twig
<form method="post" action="{{ path('app_alumnos_delete', {'id': alumno.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ alumno.id) }}">
    <button class="btn btn-primary">Delete</button>
</form>

templates/alumnos/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary" style="margin-bottom: 10px; width: 80px;">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/alumnos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Alumno{% endblock %}

{% block div %}
    <section class="section" id="about">
        <div class="container">
            <h1>Edit Alumnos</h1>

            {{ include('alumnos/_form.html.twig', {'button_label': 'Update'}) }}
            {{ include('alumnos/_delete_form.html.twig') }}

             <div style="margin-top: 20px;">
                <a href="{{ path('app_alumnos_index') }}" >Back to list</a>
            </div>
        </div>
    </section>    
{% endblock %}

templates/alumnos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Alumnos {% endblock %}

{% block div %}
    <section class="section" id="about">
        <div class="container">
            <h1>Alumnos</h1>
            <a href="{{ path('app_alumnos_new') }}" class="btn btn-primary w-lg">Create new</a>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Primer apellido</th>
                        <th>Segundo apellido</th>
                        <th>Fecha nacimiento</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for alumno in alumnos %}

                    <tr>
                        <td><strong>{{ alumno.nombre }}</strong></td>
                        <td><strong>{{ alumno.primerApellido }}</strong></td>
                        <td><strong>{{ alumno.segundoApellido }}</strong></td>
                        <td>{{ alumno.fechaNacimiento ? alumno.fechaNacimiento|date('d-M-Y') : '' }}</td>
                        <td>
                            <a href="{{ path('app_alumnos_show', {'id': alumno.id}) }}" style="margin-right: 2px;">Show /</a>
                            <a href="{{ path('app_alumnos_edit', {'id': alumno.id}) }}">Edit</a>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4">
                                <!-- empieza tabla -->
                                <table>
                                        <tr>
                                            <td><a href="tel:{{ alumno.telefono }}" title="Llamar por télefono a {{ alumno.nombre }}">{{ alumno.telefono }}</a></td>
                                            <td><a href="mailto:{{ alumno.email }}" title="Enviar a {{ alumno.nombre }} un e-mail">{{ alumno.email }}</a></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>{{ alumno.codigoPostal }}</td>
                                            <td>{{ alumno.poblacion }}</td>
                                            <td>{{ alumno.domicilio }}</td>
                                        </tr>
                                 </table>
                                <!-- termian tabla -->
                        <td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="11">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </section>

{% endblock %}

templates/alumnos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Alumnos{% endblock %}

{% block div %}
    

   <section class="section" id="about"> 
   
        <div class="container">
             <h1>Create new Alumno</h1>
            {{ include('alumnos/_form.html.twig') }}
               <div style="margin-top: 20px;">
                    <a href="{{ path('app_alumnos_index') }}">Back to list</a>
               </div>
        </div>
   
   </section>

   

   
{% endblock %}

templates/alumnos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Alumnos{% endblock %}

{% block div %}
    <section class="section" id="about">
        <div class="container">
            <h1>Alumnos</h1>

            <table class="table">
                <tbody>
                    <tr>
                        <th>Nombre</th>
                        <td>{{ alumno.nombre }}</td>
                    </tr>
                    <tr>
                        <th>Primer apellido</th>
                        <td>{{ alumno.primerApellido }}</td>
                    </tr>
                    <tr>
                        <th>Segundo apellido</th>
                        <td>{{ alumno.segundoApellido }}</td>
                    </tr>
                    <tr>
                        <th>Fecha nacimiento</th>
                        <td>{{ alumno.fechaNacimiento ? alumno.fechaNacimiento|date('Y-m-d') : '' }}</td>
                    </tr>
                    <tr>
                        <th>Domicilio</th>
                        <td>{{ alumno.domicilio }}</td>
                    </tr>
                    <tr>
                        <th>Poblacion</th>
                        <td>{{ alumno.poblacion }}</td>
                    </tr>
                    <tr>
                        <th>Codigo postal</th>
                        <td>{{ alumno.codigoPostal }}</td>
                    </tr>
                    <tr>
                        <th>Teléfono</th>
                        <td>{{ alumno.telefono }}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>{{ alumno.email }}</td>
                    </tr>
                </tbody>
            </table>
            
            <a href="{{ path('app_alumnos_edit', {'id': alumno.id}) }}" class="btn btn-outline-primary" style="font-weight: 600; margin-bottom: 10px; width: 85px;">Edit</a>
            {{ include('alumnos/_delete_form.html.twig') }}
            <div style="margin-top: 20px;">
                <a href="{{ path('app_alumnos_index') }}" >Back to list</a>
            </div>
        </div>
    </section>        

{% endblock %}